server:
  port: 7777
spring:
  datasource:
    url: jdbc:mysql://47.106.228.216:3306/duo_blog?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: Blog_admin1
    password: hQ<:V1psx0(t
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
  redis:
    host: 47.106.228.216
    port: 63791
    password: 123456

mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
oss:
  accessKey: 8yR1KS2ndJN7GhYgLk238pT2JgWfrj258FAeaeC5
  SecretKey: x8Y2uQj6wLpLTjlJG7IXF_7Npo7O_qfZWe3UzsaF
  bucket: duoblog
